package com.shopflow.common.error;

import org.springframework.http.HttpStatus;

/**
 * Standard business error codes (APPLICATION-ARCHITECTURE.md §69) plus a few needed by the implemented flows.
 */
public enum ErrorCode {
    AUTH_INVALID_OTP(HttpStatus.UNAUTHORIZED),
    AUTH_OTP_EXPIRED(HttpStatus.UNAUTHORIZED),
    AUTH_TOO_MANY_ATTEMPTS(HttpStatus.TOO_MANY_REQUESTS),
    AUTH_OTP_COOLDOWN(HttpStatus.TOO_MANY_REQUESTS),
    AUTH_OTP_DELIVERY_FAILED(HttpStatus.BAD_GATEWAY),
    AUTH_UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    AUTH_FORBIDDEN(HttpStatus.FORBIDDEN),
    AUTH_ACCOUNT_INACTIVE(HttpStatus.FORBIDDEN),
    AUTH_INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),
    AUTH_REGISTRATION_REQUIRED(HttpStatus.FORBIDDEN),

    CUSTOMER_NOT_FOUND(HttpStatus.NOT_FOUND),
    CUSTOMER_NOT_APPROVED(HttpStatus.FORBIDDEN),
    CUSTOMER_BLOCKED(HttpStatus.FORBIDDEN),
    CUSTOMER_ALREADY_REGISTERED(HttpStatus.CONFLICT),

    PRODUCT_NOT_FOUND(HttpStatus.NOT_FOUND),
    PRODUCT_INACTIVE(HttpStatus.UNPROCESSABLE_ENTITY),
    INSUFFICIENT_STOCK(HttpStatus.CONFLICT),

    ORDER_NOT_FOUND(HttpStatus.NOT_FOUND),
    ORDER_INVALID_STATUS(HttpStatus.CONFLICT),
    ORDER_CANNOT_CANCEL(HttpStatus.CONFLICT),
    CART_EMPTY(HttpStatus.UNPROCESSABLE_ENTITY),

    INVOICE_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVOICE_ALREADY_CANCELLED(HttpStatus.CONFLICT),
    INVOICE_INVALID_STATUS(HttpStatus.CONFLICT),
    INVOICE_HAS_PAYMENTS(HttpStatus.CONFLICT),
    NOTHING_TO_INVOICE(HttpStatus.UNPROCESSABLE_ENTITY),

    PAYMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    PAYMENT_INVALID_AMOUNT(HttpStatus.UNPROCESSABLE_ENTITY),
    PAYMENT_INVALID_STATUS(HttpStatus.CONFLICT),
    PAYMENT_PROVIDER_ERROR(HttpStatus.BAD_GATEWAY),
    WEBHOOK_SIGNATURE_INVALID(HttpStatus.BAD_REQUEST),

    CREDIT_LIMIT_EXCEEDED(HttpStatus.UNPROCESSABLE_ENTITY),
    CREDIT_NOT_ENABLED(HttpStatus.UNPROCESSABLE_ENTITY),

    PURCHASE_INVALID_STATUS(HttpStatus.CONFLICT),
    RETURN_INVALID_QUANTITY(HttpStatus.UNPROCESSABLE_ENTITY),
    RETURN_INVALID_STATUS(HttpStatus.CONFLICT),

    FILE_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),
    PROVIDER_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),

    TENANT_NOT_FOUND(HttpStatus.NOT_FOUND),
    TENANT_SUSPENDED(HttpStatus.FORBIDDEN),
    TENANT_NOT_MEMBER(HttpStatus.FORBIDDEN),
    TENANT_JOIN_LINK_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    MODULE_DISABLED(HttpStatus.FORBIDDEN),

    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    CONFLICT(HttpStatus.CONFLICT),
    RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }
}
